version: "3"

services:
  nginx:
    container_name: nginx
    build:
      dockerfile: ./Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - server

  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: ./api
    ports:
      - "3001:3001"
    networks:
      - server

  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "3000:3000"
    networks: 
      - server

networks: # 공유 네트워크
  server:
    driver: bridge