version: "3"

services:
  nginx:
    container_name: nginx
    image: ghcr.io/hoiheart/chukduk/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - /home/hoiheart/cert/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /home/hoiheart/cert/privkey.pem:/etc/nginx/certs/privkey.pem
    networks:
      - server

  api:
    container_name: api
    image: ghcr.io/hoiheart/chukduk/api:latest
    ports:
      - "3001:3001"
    networks:
      - server

  app:
    container_name: app
    image: ghcr.io/hoiheart/chukduk/app:latest
    ports:
      - "3000:3000"
    networks: 
      - server

networks: # 공유 네트워크
  server:
    driver: bridge