version: "3"

services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - ./api:/usr/api
      - ./.env:/usr/.env # env 파일 복사
    ports:
      - "3001:3001"
    networks: 
      - server

  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "3000:3000"
    networks: 
      - server

  nginx:
    container_name: nginx
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks: 
      - server

networks: # 공유 네트워크
  server:
    driver: bridge